/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StudySession = IDL.Record({
  'startTime' : IDL.Int,
  'isCompleted' : IDL.Bool,
  'endTime' : IDL.Int,
  'subjectName' : IDL.Text,
  'distractionCount' : IDL.Nat,
  'elapsedSeconds' : IDL.Nat,
  'endPhoto' : ExternalBlob,
  'startPhoto' : ExternalBlob,
});
export const SyllabusGoal = IDL.Record({
  'subjectName' : IDL.Text,
  'totalLectures' : IDL.Nat,
  'completedLectures' : IDL.Nat,
  'examDate' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Post = IDL.Record({
  'title' : IDL.Text,
  'subjectName' : IDL.Text,
  'body' : IDL.Text,
  'author' : IDL.Principal,
});
export const Squad = IDL.Record({
  'members' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
});
export const Badge = IDL.Text;
export const DeskItem = IDL.Text;
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'badges' : IDL.Vec(Badge),
  'lastStudyDate' : IDL.Text,
  'totalStudySeconds' : IDL.Nat,
  'longestStreak' : IDL.Nat,
  'deskItems' : IDL.Vec(DeskItem),
  'currentStreak' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudySession' : IDL.Func([StudySession], [], []),
  'addSyllabusGoal' : IDL.Func([SyllabusGoal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeSession' : IDL.Func([StudySession], [], []),
  'createPost' : IDL.Func([Post], [], []),
  'createSquad' : IDL.Func([Squad], [], []),
  'getCallerSession' : IDL.Func([], [IDL.Opt(StudySession)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeed' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'getStreakLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinSquad' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startSession' : IDL.Func([StudySession], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StudySession = IDL.Record({
    'startTime' : IDL.Int,
    'isCompleted' : IDL.Bool,
    'endTime' : IDL.Int,
    'subjectName' : IDL.Text,
    'distractionCount' : IDL.Nat,
    'elapsedSeconds' : IDL.Nat,
    'endPhoto' : ExternalBlob,
    'startPhoto' : ExternalBlob,
  });
  const SyllabusGoal = IDL.Record({
    'subjectName' : IDL.Text,
    'totalLectures' : IDL.Nat,
    'completedLectures' : IDL.Nat,
    'examDate' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Post = IDL.Record({
    'title' : IDL.Text,
    'subjectName' : IDL.Text,
    'body' : IDL.Text,
    'author' : IDL.Principal,
  });
  const Squad = IDL.Record({
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
  });
  const Badge = IDL.Text;
  const DeskItem = IDL.Text;
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'badges' : IDL.Vec(Badge),
    'lastStudyDate' : IDL.Text,
    'totalStudySeconds' : IDL.Nat,
    'longestStreak' : IDL.Nat,
    'deskItems' : IDL.Vec(DeskItem),
    'currentStreak' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudySession' : IDL.Func([StudySession], [], []),
    'addSyllabusGoal' : IDL.Func([SyllabusGoal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeSession' : IDL.Func([StudySession], [], []),
    'createPost' : IDL.Func([Post], [], []),
    'createSquad' : IDL.Func([Squad], [], []),
    'getCallerSession' : IDL.Func([], [IDL.Opt(StudySession)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeed' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'getStreakLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinSquad' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startSession' : IDL.Func([StudySession], [], []),
  });
};

export const init = ({ IDL }) => { return []; };