/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Badge = string;
export type DeskItem = string;
export type ExternalBlob = Uint8Array;
export interface Post {
  'title' : string,
  'subjectName' : string,
  'body' : string,
  'author' : Principal,
}
export interface Squad { 'members' : Array<Principal>, 'name' : string }
export interface StudySession {
  'startTime' : bigint,
  'isCompleted' : boolean,
  'endTime' : bigint,
  'subjectName' : string,
  'distractionCount' : bigint,
  'elapsedSeconds' : bigint,
  'endPhoto' : ExternalBlob,
  'startPhoto' : ExternalBlob,
}
export interface SyllabusGoal {
  'subjectName' : string,
  'totalLectures' : bigint,
  'completedLectures' : bigint,
  'examDate' : bigint,
}
export interface UserProfile {
  'displayName' : string,
  'badges' : Array<Badge>,
  'lastStudyDate' : string,
  'totalStudySeconds' : bigint,
  'longestStreak' : bigint,
  'deskItems' : Array<DeskItem>,
  'currentStreak' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStudySession' : ActorMethod<[StudySession], undefined>,
  'addSyllabusGoal' : ActorMethod<[SyllabusGoal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeSession' : ActorMethod<[StudySession], undefined>,
  'createPost' : ActorMethod<[Post], undefined>,
  'createSquad' : ActorMethod<[Squad], undefined>,
  'getCallerSession' : ActorMethod<[], [] | [StudySession]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeed' : ActorMethod<[], Array<StudySession>>,
  'getPosts' : ActorMethod<[string], Array<Post>>,
  'getStreakLeaderboard' : ActorMethod<[], Array<UserProfile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyLeaderboard' : ActorMethod<[], Array<UserProfile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinSquad' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startSession' : ActorMethod<[StudySession], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];