/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommunityPost {
  'postType' : string,
  'userName' : string,
  'duration' : string,
  'subject' : string,
  'userId' : string,
  'createdAt' : bigint,
  'photoUrl' : string,
  'caption' : string,
  'sessionId' : string,
  'postId' : string,
}
export type ExternalBlob = Uint8Array;
export interface FeedEntry {
  'startTime' : bigint,
  'isCompleted' : boolean,
  'endTime' : bigint,
  'subjectName' : string,
  'distractionCount' : bigint,
  'elapsedSeconds' : bigint,
  'endPhoto' : ExternalBlob,
  'startPhoto' : ExternalBlob,
}
export interface Post {
  'title' : string,
  'subjectName' : string,
  'body' : string,
  'author' : Principal,
}
export interface PostComment {
  'userName' : string,
  'commentId' : string,
  'userId' : string,
  'createdAt' : bigint,
  'text' : string,
  'postId' : string,
}
export interface Profile {
  'displayName' : string,
  'badges' : Array<string>,
  'lastStudyDate' : string,
  'totalStudySeconds' : bigint,
  'longestStreak' : bigint,
  'deskItems' : Array<string>,
  'currentStreak' : bigint,
}
export interface Session {
  'startTime' : bigint,
  'isCompleted' : boolean,
  'endTime' : bigint,
  'subjectName' : string,
  'distractionCount' : bigint,
  'elapsedSeconds' : bigint,
  'endPhoto' : ExternalBlob,
  'startPhoto' : ExternalBlob,
}
export interface Squad { 'members' : Array<Principal>, 'name' : string }
export interface SyllabusGoal {
  'subjectName' : string,
  'userId' : string,
  'createdAt' : bigint,
  'totalLectures' : bigint,
  'completedLectures' : bigint,
  'examDate' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], PostComment>,
  'addStudySession' : ActorMethod<[FeedEntry], undefined>,
  'addSyllabusGoal' : ActorMethod<[SyllabusGoal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeSession' : ActorMethod<[Session], undefined>,
  'createCommunityPost' : ActorMethod<[CommunityPost], undefined>,
  'createPost' : ActorMethod<[Post], undefined>,
  'createSquad' : ActorMethod<[Squad], undefined>,
  'deleteComment' : ActorMethod<[string], undefined>,
  'deleteCommunityPost' : ActorMethod<[string], undefined>,
  'getCallerSession' : ActorMethod<[], [] | [Session]>,
  'getCallerSyllabusGoals' : ActorMethod<[], Array<SyllabusGoal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[string], Array<PostComment>>,
  'getCommunityFeed' : ActorMethod<[], Array<CommunityPost>>,
  'getCommunityFeedWithAuth' : ActorMethod<[], Array<CommunityPost>>,
  'getFeed' : ActorMethod<[], Array<FeedEntry>>,
  'getPostLikeCount' : ActorMethod<
    [string],
    { 'count' : bigint, 'liked' : boolean }
  >,
  'getPosts' : ActorMethod<[string], Array<Post>>,
  'getStreakLeaderboard' : ActorMethod<[], Array<Profile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getWeeklyLeaderboard' : ActorMethod<[], Array<Profile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinSquad' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'startSession' : ActorMethod<[Session], undefined>,
  'togglePostLike' : ActorMethod<[string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];