/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PostComment = IDL.Record({
  'userName' : IDL.Text,
  'commentId' : IDL.Text,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'postId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FeedEntry = IDL.Record({
  'startTime' : IDL.Int,
  'isCompleted' : IDL.Bool,
  'endTime' : IDL.Int,
  'subjectName' : IDL.Text,
  'distractionCount' : IDL.Nat,
  'elapsedSeconds' : IDL.Nat,
  'endPhoto' : ExternalBlob,
  'startPhoto' : ExternalBlob,
});
export const SyllabusGoal = IDL.Record({
  'subjectName' : IDL.Text,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalLectures' : IDL.Nat,
  'completedLectures' : IDL.Nat,
  'examDate' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Session = IDL.Record({
  'startTime' : IDL.Int,
  'isCompleted' : IDL.Bool,
  'endTime' : IDL.Int,
  'subjectName' : IDL.Text,
  'distractionCount' : IDL.Nat,
  'elapsedSeconds' : IDL.Nat,
  'endPhoto' : ExternalBlob,
  'startPhoto' : ExternalBlob,
});
export const CommunityPost = IDL.Record({
  'postType' : IDL.Text,
  'userName' : IDL.Text,
  'duration' : IDL.Text,
  'subject' : IDL.Text,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'photoUrl' : IDL.Text,
  'caption' : IDL.Text,
  'sessionId' : IDL.Text,
  'postId' : IDL.Text,
});
export const Post = IDL.Record({
  'title' : IDL.Text,
  'subjectName' : IDL.Text,
  'body' : IDL.Text,
  'author' : IDL.Principal,
});
export const Squad = IDL.Record({
  'members' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
});
export const Profile = IDL.Record({
  'displayName' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'lastStudyDate' : IDL.Text,
  'totalStudySeconds' : IDL.Nat,
  'longestStreak' : IDL.Nat,
  'deskItems' : IDL.Vec(IDL.Text),
  'currentStreak' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [PostComment], []),
  'addStudySession' : IDL.Func([FeedEntry], [], []),
  'addSyllabusGoal' : IDL.Func([SyllabusGoal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeSession' : IDL.Func([Session], [], []),
  'createCommunityPost' : IDL.Func([CommunityPost], [], []),
  'createPost' : IDL.Func([Post], [], []),
  'createSquad' : IDL.Func([Squad], [], []),
  'deleteComment' : IDL.Func([IDL.Text], [], []),
  'deleteCommunityPost' : IDL.Func([IDL.Text], [], []),
  'getCallerSession' : IDL.Func([], [IDL.Opt(Session)], ['query']),
  'getCallerSyllabusGoals' : IDL.Func([], [IDL.Vec(SyllabusGoal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(PostComment)], ['query']),
  'getCommunityFeed' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
  'getCommunityFeedWithAuth' : IDL.Func(
      [],
      [IDL.Vec(CommunityPost)],
      ['query'],
    ),
  'getFeed' : IDL.Func([], [IDL.Vec(FeedEntry)], ['query']),
  'getPostLikeCount' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'count' : IDL.Nat, 'liked' : IDL.Bool })],
      ['query'],
    ),
  'getPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'getStreakLeaderboard' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getWeeklyLeaderboard' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinSquad' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'startSession' : IDL.Func([Session], [], []),
  'togglePostLike' : IDL.Func([IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PostComment = IDL.Record({
    'userName' : IDL.Text,
    'commentId' : IDL.Text,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'postId' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FeedEntry = IDL.Record({
    'startTime' : IDL.Int,
    'isCompleted' : IDL.Bool,
    'endTime' : IDL.Int,
    'subjectName' : IDL.Text,
    'distractionCount' : IDL.Nat,
    'elapsedSeconds' : IDL.Nat,
    'endPhoto' : ExternalBlob,
    'startPhoto' : ExternalBlob,
  });
  const SyllabusGoal = IDL.Record({
    'subjectName' : IDL.Text,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalLectures' : IDL.Nat,
    'completedLectures' : IDL.Nat,
    'examDate' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Session = IDL.Record({
    'startTime' : IDL.Int,
    'isCompleted' : IDL.Bool,
    'endTime' : IDL.Int,
    'subjectName' : IDL.Text,
    'distractionCount' : IDL.Nat,
    'elapsedSeconds' : IDL.Nat,
    'endPhoto' : ExternalBlob,
    'startPhoto' : ExternalBlob,
  });
  const CommunityPost = IDL.Record({
    'postType' : IDL.Text,
    'userName' : IDL.Text,
    'duration' : IDL.Text,
    'subject' : IDL.Text,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'photoUrl' : IDL.Text,
    'caption' : IDL.Text,
    'sessionId' : IDL.Text,
    'postId' : IDL.Text,
  });
  const Post = IDL.Record({
    'title' : IDL.Text,
    'subjectName' : IDL.Text,
    'body' : IDL.Text,
    'author' : IDL.Principal,
  });
  const Squad = IDL.Record({
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
  });
  const Profile = IDL.Record({
    'displayName' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'lastStudyDate' : IDL.Text,
    'totalStudySeconds' : IDL.Nat,
    'longestStreak' : IDL.Nat,
    'deskItems' : IDL.Vec(IDL.Text),
    'currentStreak' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [PostComment], []),
    'addStudySession' : IDL.Func([FeedEntry], [], []),
    'addSyllabusGoal' : IDL.Func([SyllabusGoal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeSession' : IDL.Func([Session], [], []),
    'createCommunityPost' : IDL.Func([CommunityPost], [], []),
    'createPost' : IDL.Func([Post], [], []),
    'createSquad' : IDL.Func([Squad], [], []),
    'deleteComment' : IDL.Func([IDL.Text], [], []),
    'deleteCommunityPost' : IDL.Func([IDL.Text], [], []),
    'getCallerSession' : IDL.Func([], [IDL.Opt(Session)], ['query']),
    'getCallerSyllabusGoals' : IDL.Func([], [IDL.Vec(SyllabusGoal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(PostComment)], ['query']),
    'getCommunityFeed' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
    'getCommunityFeedWithAuth' : IDL.Func(
        [],
        [IDL.Vec(CommunityPost)],
        ['query'],
      ),
    'getFeed' : IDL.Func([], [IDL.Vec(FeedEntry)], ['query']),
    'getPostLikeCount' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'count' : IDL.Nat, 'liked' : IDL.Bool })],
        ['query'],
      ),
    'getPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'getStreakLeaderboard' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getWeeklyLeaderboard' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinSquad' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'startSession' : IDL.Func([Session], [], []),
    'togglePostLike' : IDL.Func([IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };